from __future__ import annotations

from .tool_profiles import TOOL_CATALOG, VALID_TOOLSETS


def render_tool_catalog_markdown() -> str:
    """Render the governed MCP tool catalog as deterministic Markdown."""
    lines = [
        "# Generated MCP Tool Catalog",
        "",
        "<!-- Generated by scripts/generate_tool_catalog.py. Do not edit manually. -->",
        "",
        "This reference is generated from the runtime tool catalog. `core` marks tools exposed by",
        "default; other tools require a selected domain toolset at server startup.",
        "",
    ]
    for toolset in sorted(VALID_TOOLSETS):
        lines.extend(
            [
                f"## {toolset}",
                "",
                "| Tool | Default | Safety | Stability | Owner | Schema | Deprecated |",
                "|---|---:|---|---|---|---:|---:|",
            ]
        )
        for name, spec in sorted(TOOL_CATALOG.items()):
            if toolset not in spec.toolsets:
                continue
            lines.append(
                f"| `{name}` | {'yes' if spec.default_enabled else 'no'} | "
                f"{spec.safety_level} | {spec.stability} | `{spec.owner}` | "
                f"{spec.schema_version} | {'yes' if spec.deprecated else 'no'} |"
            )
        lines.append("")
    return "\n".join(lines)
